<a href="https://colab.research.google.com/github/Alejandro202909/ale/blob/main/Tarea_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version

Python 3.10.12


In [2]:
import numpy as np

In [4]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
import numpy as np
matrix = np.ones((3, 3), dtype=bool)
print(matrix)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [28]:
import numpy as np
array = np.arange(10)
# Filtrar los números impares
odds = array[array % 2 != 0]
print(odds)

[1 3 5 7 9]


In [29]:
import numpy as np
array = np.arange(10)
# Filtrar los números impares
odds = array[array % 2 != 0] - 1
print(odds)

[0 2 4 6 8]


In [33]:
import numpy as np
array = np.arange(10)
# Convertir la matriz 1D en una matriz 2D con 2 filas
arr_2d = np.reshape(array, (2, -1))

print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [34]:
a=np.random.randint(low=4,high=12,size=(2,2))
a

array([[6, 5],
       [7, 6]])

In [35]:
b=np.random.randint(low=4,high=12,size=(2,2))
b

array([[ 8,  4],
       [11,  9]])

In [36]:
aux=np.vstack((a,b))
print(aux)

[[ 6  5]
 [ 7  6]
 [ 8  4]
 [11  9]]


In [38]:
aux=np.hstack((a,b))
print(aux)

[[ 6  5  8  4]
 [ 7  6 11  9]]


In [43]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# Obtener los elementos entre las posiciones 5 y 10
articulos = a[5:10]

print(articulos)

[6, 7, 8, 9, 10]


In [44]:
import numpy as np

def maxx(x,y):
    """Get the maximum of two items"""
    if x >= y:
         return x
    else:
         return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
    #maxx(a,b)
tmp=list()
for i in range(len(a)):
   tmp.append(maxx(a[i],b[i]))

print(tmp)

[6, 7, 9, 8, 9, 7, 5]


In [46]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Intercambiar las columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print(arr)

[[1 3 2]
 [4 6 5]
 [7 9 8]]


In [47]:
import numpy as np

# Crear una matriz 2D de forma 5x3 con números decimales aleatorios entre 0 y 5
matriz = np.random.rand(5, 3) * 5

print(matriz)

[[4.1493315  1.35588728 4.664797  ]
 [4.79972498 3.47201885 3.85059741]
 [0.92409673 2.48422986 0.06037249]
 [0.67874913 0.57786137 0.73047621]
 [0.20000533 2.18155659 3.79594961]]
