<a href="https://colab.research.google.com/github/Alejandro202909/ale/blob/main/tutorias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version

Python 3.10.12


In [3]:
import numpy as np
alejo=boda.array([3,33,333])
print(alejo)
print(alejo.shape)


[  3  33 333]
(3,)


In [5]:
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print(b)
print(b[:,[2,3]])

(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]


In [9]:
c=np.random.randint(low=4,high=12,size=(2,2))
c

array([[4, 4],
       [9, 7]])

In [8]:
b=np.random.randint(low=1,high=8,size=(2,2))
b

array([[4, 1],
       [5, 2]])

In [10]:
aux=np.vstack((c,b))
aux


array([[4, 4],
       [9, 7],
       [4, 1],
       [5, 2]])

In [12]:
aux=np.hstack((c,b))
aux

array([[4, 4, 4, 1],
       [9, 7, 5, 2]])